# Generated by Django 6.0.5 on 2026-05-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(default='No description', max_length=100),
            preserve_default=False,
        ),
    ]
