# Generated by Django 6.0.5 on 2026-05-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='comment',
            new_name='text',
        ),
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='Review title', max_length=100),
            preserve_default=False,
        ),
    ]
