# Generated by Django 6.0.5 on 2026-06-03 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_review_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
